// Generated by gencpp from file surena_usb/active_csp.msg
// DO NOT EDIT!


#ifndef SURENA_USB_MESSAGE_ACTIVE_CSP_H
#define SURENA_USB_MESSAGE_ACTIVE_CSP_H

#include <ros/service_traits.h>


#include <surena_usb/active_cspRequest.h>
#include <surena_usb/active_cspResponse.h>


namespace surena_usb
{

struct active_csp
{

typedef active_cspRequest Request;
typedef active_cspResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct active_csp
} // namespace surena_usb


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::surena_usb::active_csp > {
  static const char* value()
  {
    return "9d17c7a086f295f3ddeb8ac344bfc6ca";
  }

  static const char* value(const ::surena_usb::active_csp&) { return value(); }
};

template<>
struct DataType< ::surena_usb::active_csp > {
  static const char* value()
  {
    return "surena_usb/active_csp";
  }

  static const char* value(const ::surena_usb::active_csp&) { return value(); }
};


// service_traits::MD5Sum< ::surena_usb::active_cspRequest> should match 
// service_traits::MD5Sum< ::surena_usb::active_csp > 
template<>
struct MD5Sum< ::surena_usb::active_cspRequest>
{
  static const char* value()
  {
    return MD5Sum< ::surena_usb::active_csp >::value();
  }
  static const char* value(const ::surena_usb::active_cspRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::surena_usb::active_cspRequest> should match 
// service_traits::DataType< ::surena_usb::active_csp > 
template<>
struct DataType< ::surena_usb::active_cspRequest>
{
  static const char* value()
  {
    return DataType< ::surena_usb::active_csp >::value();
  }
  static const char* value(const ::surena_usb::active_cspRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::surena_usb::active_cspResponse> should match 
// service_traits::MD5Sum< ::surena_usb::active_csp > 
template<>
struct MD5Sum< ::surena_usb::active_cspResponse>
{
  static const char* value()
  {
    return MD5Sum< ::surena_usb::active_csp >::value();
  }
  static const char* value(const ::surena_usb::active_cspResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::surena_usb::active_cspResponse> should match 
// service_traits::DataType< ::surena_usb::active_csp > 
template<>
struct DataType< ::surena_usb::active_cspResponse>
{
  static const char* value()
  {
    return DataType< ::surena_usb::active_csp >::value();
  }
  static const char* value(const ::surena_usb::active_cspResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SURENA_USB_MESSAGE_ACTIVE_CSP_H
