// Generated by gencpp from file surena_usb/reset_nodeRequest.msg
// DO NOT EDIT!


#ifndef SURENA_USB_MESSAGE_RESET_NODEREQUEST_H
#define SURENA_USB_MESSAGE_RESET_NODEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace surena_usb
{
template <class ContainerAllocator>
struct reset_nodeRequest_
{
  typedef reset_nodeRequest_<ContainerAllocator> Type;

  reset_nodeRequest_()
    : nodeID(0)  {
    }
  reset_nodeRequest_(const ContainerAllocator& _alloc)
    : nodeID(0)  {
  (void)_alloc;
    }



   typedef int32_t _nodeID_type;
  _nodeID_type nodeID;





  typedef boost::shared_ptr< ::surena_usb::reset_nodeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::surena_usb::reset_nodeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct reset_nodeRequest_

typedef ::surena_usb::reset_nodeRequest_<std::allocator<void> > reset_nodeRequest;

typedef boost::shared_ptr< ::surena_usb::reset_nodeRequest > reset_nodeRequestPtr;
typedef boost::shared_ptr< ::surena_usb::reset_nodeRequest const> reset_nodeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::surena_usb::reset_nodeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::surena_usb::reset_nodeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace surena_usb

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::surena_usb::reset_nodeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::surena_usb::reset_nodeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::surena_usb::reset_nodeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::surena_usb::reset_nodeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::surena_usb::reset_nodeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::surena_usb::reset_nodeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::surena_usb::reset_nodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "83f1d0e77402d46c26211c4c64e0f71c";
  }

  static const char* value(const ::surena_usb::reset_nodeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x83f1d0e77402d46cULL;
  static const uint64_t static_value2 = 0x26211c4c64e0f71cULL;
};

template<class ContainerAllocator>
struct DataType< ::surena_usb::reset_nodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "surena_usb/reset_nodeRequest";
  }

  static const char* value(const ::surena_usb::reset_nodeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::surena_usb::reset_nodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 nodeID\n\
";
  }

  static const char* value(const ::surena_usb::reset_nodeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::surena_usb::reset_nodeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nodeID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct reset_nodeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::surena_usb::reset_nodeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::surena_usb::reset_nodeRequest_<ContainerAllocator>& v)
  {
    s << indent << "nodeID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.nodeID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SURENA_USB_MESSAGE_RESET_NODEREQUEST_H
