// Generated by gencpp from file offlinepublisher/srv1.msg
// DO NOT EDIT!


#ifndef OFFLINEPUBLISHER_MESSAGE_SRV1_H
#define OFFLINEPUBLISHER_MESSAGE_SRV1_H

#include <ros/service_traits.h>


#include <offlinepublisher/srv1Request.h>
#include <offlinepublisher/srv1Response.h>


namespace offlinepublisher
{

struct srv1
{

typedef srv1Request Request;
typedef srv1Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srv1
} // namespace offlinepublisher


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::offlinepublisher::srv1 > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::offlinepublisher::srv1&) { return value(); }
};

template<>
struct DataType< ::offlinepublisher::srv1 > {
  static const char* value()
  {
    return "offlinepublisher/srv1";
  }

  static const char* value(const ::offlinepublisher::srv1&) { return value(); }
};


// service_traits::MD5Sum< ::offlinepublisher::srv1Request> should match 
// service_traits::MD5Sum< ::offlinepublisher::srv1 > 
template<>
struct MD5Sum< ::offlinepublisher::srv1Request>
{
  static const char* value()
  {
    return MD5Sum< ::offlinepublisher::srv1 >::value();
  }
  static const char* value(const ::offlinepublisher::srv1Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::offlinepublisher::srv1Request> should match 
// service_traits::DataType< ::offlinepublisher::srv1 > 
template<>
struct DataType< ::offlinepublisher::srv1Request>
{
  static const char* value()
  {
    return DataType< ::offlinepublisher::srv1 >::value();
  }
  static const char* value(const ::offlinepublisher::srv1Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::offlinepublisher::srv1Response> should match 
// service_traits::MD5Sum< ::offlinepublisher::srv1 > 
template<>
struct MD5Sum< ::offlinepublisher::srv1Response>
{
  static const char* value()
  {
    return MD5Sum< ::offlinepublisher::srv1 >::value();
  }
  static const char* value(const ::offlinepublisher::srv1Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::offlinepublisher::srv1Response> should match 
// service_traits::DataType< ::offlinepublisher::srv1 > 
template<>
struct DataType< ::offlinepublisher::srv1Response>
{
  static const char* value()
  {
    return DataType< ::offlinepublisher::srv1 >::value();
  }
  static const char* value(const ::offlinepublisher::srv1Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OFFLINEPUBLISHER_MESSAGE_SRV1_H
